blank_issues_enabled: false
contact_links:
  - name: 我的项目介绍
    url: https://tools.hejunjie.life
    about: 在这里你可以更好地了解我的作品
  - name: 我的个人网站
    url: https://hejunjie.life
    about: 欢迎来我家坐坐，了解我和我的作品
