name: Waka Readme

on:
  schedule:
    - cron: "0 0 * * *" # 每天 UTC 0 点更新（可自行改）
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
